CREATE TABLE users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email character varying(100) NOT NULL,
    name character varying(100) NOT NULL,
    CONSTRAINT users_email_unique UNIQUE (email)
);