CREATE TABLE requests
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description character varying(200) NOT NULL,
    user_id bigint NOT NULL,
    created timestamp without time zone DEFAULT now(),
    CONSTRAINT fk_requests_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_requests_user_id ON requests (user_id);