CREATE TABLE items
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL,
    description character varying(200) NOT NULL,
    available boolean DEFAULT true,
    owner_id bigint NOT NULL,
    request_id bigint,
    CONSTRAINT fk_item_user FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_item_request FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE SET NULL
);

CREATE INDEX idx_items_owner_id ON items (owner_id);