CREATE TABLE bookings
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start timestamp NOT NULL,
    end_time timestamp NOT NULL,
    user_id bigint NOT NULL,
    item_id bigint NOT NULL,
    status integer DEFAULT 0,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_item_id FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE RESTRICT
);

CREATE INDEX idx_booking_user_id ON bookings (user_id);
CREATE INDEX idx_booking_item_id ON bookings (item_id);