CREATE TABLE comments
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar(256) NOT NULL,
    item_id bigint NOT NULL,
    user_id bigint NOT NULL,
    created timestamp DEFAULT now(),
    CONSTRAINT fk_comm_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_comm_item_id FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT unique_item_user UNIQUE (item_id, user_id)
);
CREATE INDEX idx_comm_items ON comments (item_id);